# Generated by Django 5.2.3 on 2025-06-23 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('publication_date', models.DateField(verbose_name='Date de publication')),
                ('media_type', models.CharField(choices=[('BOOK', 'Livre'), ('CD', 'CD'), ('DVD', 'DVD'), ('BOARDGAME', 'Jeu de plateau')], max_length=20, verbose_name='Type de média')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medialibrary.media')),
                ('min_players', models.IntegerField(verbose_name='Joueurs minimum')),
                ('max_players', models.IntegerField(verbose_name='Joueurs maximum')),
                ('duration', models.IntegerField(verbose_name='Durée moyenne (minutes)')),
            ],
            options={
                'verbose_name': 'Jeu de plateau',
                'verbose_name_plural': 'Jeux de plateau',
            },
            bases=('medialibrary.media',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medialibrary.media')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('page_count', models.IntegerField(verbose_name='Nombre de pages')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
            },
            bases=('medialibrary.media',),
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medialibrary.media')),
                ('duration', models.IntegerField(verbose_name='Durée (minutes)')),
                ('track_count', models.IntegerField(verbose_name='Nombre de pistes')),
            ],
            options={
                'verbose_name': 'CD',
                'verbose_name_plural': 'CDs',
            },
            bases=('medialibrary.media',),
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medialibrary.media')),
                ('duration', models.IntegerField(verbose_name='Durée (minutes)')),
                ('video_format', models.CharField(max_length=10, verbose_name='Format vidéo')),
            ],
            options={
                'verbose_name': 'DVD',
                'verbose_name_plural': 'DVDs',
            },
            bases=('medialibrary.media',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('membership_date', models.DateField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('can_borrow', models.BooleanField(default=True, verbose_name='Peut emprunter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name="Date d'emprunt")),
                ('due_date', models.DateField(verbose_name='Date de retour prévue')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Date de retour effectif')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialibrary.media', verbose_name='Média')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialibrary.member', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-loan_date'],
            },
        ),
    ]
